<h1>Editar categoria</h1>
<hr />
<?php
$form = $this->form->getForm();
//print_r($form); die;
//$entity = $this->entity;
//$form->setAttribute('action', $this->url('application', array('action' => 'editar')))->prepare();
$form->setAttribute('action', $this->url('application/default', array('controller' => 'index', 'action' => 'editar', 'id' => $this->id)));
echo $this->form()->openTag($form);

//echo '<form action="/application/index/editar/1" method="post">';
//echo $this->formHidden($form->get('id'));
//echo $this->formRow($form->get('Id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('description'));
echo $this->formInput($form->get('submit'));
echo $this->form()->closeTag($form);